import { SamAbility } from "../sam_types";
import { gemdraught1str } from "@xivgear/core/sims/common/potion";
import {
    Gekko, Gyofu, Higanbana,
    HissatsuGyoten, HissatsuSenei, HissatsuShinten,
    Ikishoten, Jinpu, KaeshiNamikiri, Kasha,
    MeikyoShisui, MidareSetsugekka, OgiNamikiri,
    Shifu, Shoha, TendoKaeshiSetsugekka,
    TendoSetsugekka, Yukikaze, Zanshin,
} from '../sam_actions';

export const ActionList: SamAbility[] = [
    MeikyoShisui,
    Gekko,
    Ikishoten,
    gemdraught1str,
    Kasha,
    Yukikaze,
    TendoSetsugekka,
    HissatsuSenei,
    TendoKaeshiSetsugekka,
    MeikyoShisui,
    Gekko,
    Zanshin,
    Higanbana,
    OgiNamikiri,
    Shoha,
    KaeshiNamikiri,
    Kasha,
    HissatsuShinten,
    Gekko,
    HissatsuGyoten,
    Gyofu,
    Yukikaze,
    HissatsuShinten,
    TendoSetsugekka,
    TendoKaeshiSetsugekka,
    Gyofu,
    Jinpu,
    Gekko,
    Gyofu,
    Shifu,
    Kasha,
    Gyofu,
    Yukikaze,
    MidareSetsugekka,
    Gyofu,
    Yukikaze,
    Gyofu,
    Jinpu,
    HissatsuGyoten,
    Gekko,
    Gyofu,
    Shifu,
    HissatsuShinten,
    Kasha,
    MeikyoShisui,
    TendoSetsugekka,
    HissatsuSenei,
    TendoKaeshiSetsugekka,
    Shoha,
    Gekko,
    HissatsuShinten,
    Higanbana,
    HissatsuShinten,
    Gekko,
    HissatsuGyoten,
    Kasha,
    HissatsuShinten,
    Gyofu,
    Yukikaze,
    MidareSetsugekka,
    Gyofu,
    Yukikaze,
    Gyofu,
    Shifu,
    Kasha,
    Gyofu,
    Jinpu,
    Gekko,
    MidareSetsugekka,
    Shoha,
    Gyofu,
    HissatsuShinten,
    Yukikaze,
    HissatsuShinten,
    Gyofu,
    HissatsuShinten,
    Shifu,
    Kasha,
    Gyofu,
    Jinpu,
    Gekko,
    MidareSetsugekka,
    Gyofu,
    Yukikaze,
    MeikyoShisui,
    Gekko,
];

export default ActionList;