name: Test Build for PR

on:
  push:
  pull_request:
#    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0

      - name: Build
        run: |
          npm install
          npm install --workspaces
          npm run --workspace=gearplan-frontend build
          npm run --workspace=gearplan-frontend less
          npm run --workspace=gearplan-frontend test
