name: Lint

on:
  push:
  pull_request:
#    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - uses: pnpm/action-setup@v5

      - name: Build
        run: |
          pnpm install
          pnpm lint
